apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-config
  namespace: home-assistant
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
