apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-grafana-egress
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  policyTypes:
    - Egress
  egress:
    # Allow Grafana to talk to Prometheus, Alertmanager, and other monitoring services
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: alertmanager
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kube-state-metrics
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: node-exporter
      ports:
        - protocol: TCP
          port: 9090
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 9093
    # Allow to download dashboards
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 443
          protocol: TCP
