apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-grafana-ingress
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  policyTypes:
    - Ingress
  ingress:
    # Allow from Traefik (main ingress controller)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - port: 80
          protocol: TCP
        - port: 3000
          protocol: TCP

    # Allow from svclb-traefik pods (node load balancer helpers)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              svccontroller.k3s.cattle.io/svcname: traefik
      ports:
        - port: 80
          protocol: TCP
        - port: 3000
          protocol: TCP

    # Allow intra-namespace traffic (metrics, probes, etc.)
    - from:
        - podSelector: {}
      ports:
        - port: 80
          protocol: TCP
        - port: 3000
          protocol: TCP
