apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  interval: 10m
  chart:
    spec:
      chart: minecraft
      version: "5.x.x"
      sourceRef:
        kind: HelmRepository
        name: itzg-minecraft-repo
        namespace: minecraft
  valuesFrom:
    - kind: ConfigMap
      name: minecraft-values
