prometheus:
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
          storageClassName: "local-path"
alertmanager:
  enabled: true
  alertmanagerSpec:
    secrets:
      - alertmanager-email-creds
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
          storageClassName: "local-path"
  config:
    global:
      resolve_timeout: 5m
      smtp_from: "ross.mage@gmail.com"
      smtp_smarthost: "smtp.gmail.com:587"
      smtp_auth_username: "ross.mage@gmail.com"
      smtp_auth_password_file: "/etc/alertmanager/secrets/alertmanager-email-creds/email_pass"
    route:
      group_by: ["job"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: "email-notifications"
    receivers:
      - name: "email-notifications"
        email_configs:
          - to: "polar-swipe-ranch@duck.com"
            send_resolved: true
      - name: "null"
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - alerts.lan
    path: /
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
grafana:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.lan
    path: /
  initChownData:
    enabled: false
  podSecurityContext:
    fsGroup: 472
    runAsGroup: 472
    runAsUser: 472
  securityContext:
    fsGroup: 472
    runAsGroup: 472
    runAsUser: 472
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 2Gi
  persistence:
    enabled: true
    size: 20Gi
    accessModes:
      - ReadWriteOnce
    storageClassName: "local-path"
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
