apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: trivy-operator
    namespace: trivy
  valuesFrom:
    - kind: ConfigMap
      name: trivy-values
