serviceMonitor:
  enabled: true
trivy:
  mode: ClientServer
  image:
    registry: ghcr.io
    repository: aquasecurity/trivy
  dbRegistry: ghcr.io
  dbRepository: aquasecurity/trivy-db
  javaDbRegistry: ghcr.io
  javaDbRepository: aquasecurity/trivy-java-db
  ignoreUnfixed: true
  podLabels:
    app: trivy
  timeout: "30m"
  severity: "MEDIUM,HIGH,CRITICAL"
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
trivyServer:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 256Mi
operator:
  scanJobTimeout: "30m"
  infraAssessmentScannerEnabled: false
