serviceMonitor:
  enabled: true
trivy:
  ignoreUnfixed: true
  podLabels:
    app: trivy
  timeout: "30m"
  severity: "MEDIUM,HIGH,CRITICAL"
  repository: ghcr.io/aquasecurity/trivy
  dbRepository: ghcr.io/aquasecurity/trivy-db
  javaDbRepository: ghcr.io/aquasecurity/trivy-java-db
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 256Mi
operator:
  scanJobTimeout: "30m"
  infraAssessmentScannerEnabled: false
