apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "77.x.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 10m
  values:
    prometheus:
      resources:
        limits:
          memory: 2Gi
