apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: prometheus-community
    namespace: monitoring
  values:
    prometheus:
      resources:
        limits:
          memory: 2Gi
