apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: prometheus-community
    namespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: monitoring-prometheus-values
    - kind: ConfigMap
      name: monitoring-grafana-values
    - kind: ConfigMap
      name: monitoring-alertmanager-values
    - kind: ConfigMap
      name: monitoring-dashboards
    - kind: ConfigMap
      name: alert-rules
