apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: prometheus-community
    namespace: monitoring
  values:
    prometheus:
      resources:
        limits:
          memory: 2Gi
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.lan
        path: /
      persistence:
        enabled: true
        size: 20Gi
        accessModes:
          - ReadWriteOnce
        storageClassName: "local-path"
      resources:
        limits:
          memory: 1Gi
