apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 60m
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
  type: oci
