apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: robusta
  namespace: monitoring
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: robusta
      version: "0.35.x"
      sourceRef:
        kind: HelmRepository
        name: robusta
        namespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: robusta-values
    - kind: Secret
      name: robusta-secret-values
      optional: true
