apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helm-release.yaml
  - helm-source.yaml
  - namespace.yaml
configMapGenerator:
  - name: monitoring-values
    files:
      - values.yaml=../../sandbox/monitoring/values.yaml
  - name: monitoring-dashboards
    files:
      - values.yaml=../../sandbox/monitoring/dashboards.yaml
